// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfbrsjjerrsvzakuovpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmYnJzamplcnJzdnpha3VvdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzAzNTgsImV4cCI6MjA3MzU0NjM1OH0.640qYtoCsLXP04d83SWjdTmOT01TCcy0CwPUrddl7Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});